/**
 * Reads `docs/research/khan-academy-import.json` (produced by import-khan.ts)
 * and writes `supabase/seed.sql`.
 *
 * Deterministic — running twice produces byte-identical output.
 *
 * Strategy:
 *   1. Wipe existing preset content (lessons → courses → topics, plus
 *      lesson_progress and profile_courses for those courses).
 *   2. Upsert 5 topic_groups (PR1 already inserts these; we re-upsert here so
 *      a fresh `supabase db reset` ends up with consistent state regardless of
 *      whether PR1's seed ran before).
 *   3. Insert 24 topics (linked to groups).
 *   4. Insert ~170 courses (linked to topics).
 *   5. Insert ~1700 lessons (linked to courses).
 *
 * Usage:
 *   npx tsx scripts/build-seed.ts
 */

import { promises as fs } from 'node:fs';
import { join } from 'node:path';

const WORKTREE = process.cwd();
const INPUT_PATH = join(WORKTREE, 'docs', 'research', 'khan-academy-import.json');
const OUTPUT_PATH = join(WORKTREE, 'supabase', 'seed.sql');

// ---------- Types (must match import-khan.ts ImportData) ----------

type LessonOut = { id: string; title: string; ytId: string; durationSeconds: number; position: number };
type CourseOut = { id: string; title: string; position: number; ytPlaylistId: string; truncatedFrom: number | null; lessons: LessonOut[] };
type TopicOut = { id: string; title: string; position: number; icon: string; courses: CourseOut[] };
type GroupOut = { key: string; title: string; position: number; icon: string; topics: TopicOut[] };
type ImportData = { importedAt: string; groups: GroupOut[]; stats: any };

// ---------- SQL helpers ----------

// Single-quote escape for Postgres string literals.
function q(s: string | null): string {
  if (s === null) return 'null';
  return `'${s.replace(/'/g, "''")}'`;
}

function uuid(s: string): string {
  return `'${s}'`;
}

function int(n: number): string {
  return String(Math.trunc(n));
}

// ---------- Main ----------

async function main() {
  const data: ImportData = JSON.parse(await fs.readFile(INPUT_PATH, 'utf8'));

  const lines: string[] = [];
  lines.push(
    '-- supabase/seed.sql — generated by scripts/build-seed.ts',
    '-- DO NOT EDIT BY HAND. Re-run `npx tsx scripts/build-seed.ts` to regenerate.',
    `-- Imported from Khan Academy on ${data.importedAt}`,
    '',
    '-- ===== Wipe existing preset content =====',
    '-- Cascades correctly because RLS is bypassed by db reset; explicit deletes',
    '-- in dependency order so we do not orphan FKs.',
    'delete from public.lesson_progress where lesson_id in (',
    '  select l.id from public.lessons l',
    '  join public.courses c on c.id = l.course_id',
    '  where c.is_preset = true',
    ');',
    'delete from public.profile_courses where course_id in (',
    '  select id from public.courses where is_preset = true',
    ');',
    'delete from public.lessons where course_id in (',
    '  select id from public.courses where is_preset = true',
    ');',
    'delete from public.courses where is_preset = true;',
    'delete from public.topics where is_preset = true;',
    '-- topic_groups are upserted below (PR1 also seeded them).',
    '',
  );

  // ===== Topic groups =====
  lines.push('-- ===== Topic groups (5 preset super-categories) =====');
  lines.push('insert into public.topic_groups (id, owner_id, is_preset, key, title, position, icon) values');
  // Use stable hard-coded IDs matching what PR1's seed.sql used so existing
  // FK references stay valid.
  const groupIds: Record<string, string> = {
    finance:    '00000000-0000-0000-0000-0000000000a1',
    humanities: '00000000-0000-0000-0000-0000000000a2',
    stem:       '00000000-0000-0000-0000-0000000000a3',
    math:       '00000000-0000-0000-0000-0000000000a4',
    cs:         '00000000-0000-0000-0000-0000000000a5',
  };
  const groupRows = data.groups.map((g) =>
    `  (${uuid(groupIds[g.key])}, null, true, ${q(g.key)}, ${q(g.title)}, ${int(g.position)}, ${q(g.icon)})`,
  );
  lines.push(groupRows.join(',\n'));
  lines.push(
    'on conflict (id) do update set',
    '  key = excluded.key,',
    '  title = excluded.title,',
    '  position = excluded.position,',
    '  icon = excluded.icon;',
    '',
  );

  // ===== Topics =====
  lines.push('-- ===== Topics (24 preset, linked to groups) =====');
  lines.push('insert into public.topics (id, owner_id, is_preset, title, icon, color, position, group_id) values');
  const topicRows: string[] = [];
  // Continuous global position across all topics so ordering on home (which
  // sorts by topic.position) follows the group sequence.
  let globalTopicPos = 0;
  for (const g of data.groups) {
    for (const t of g.topics) {
      topicRows.push(
        `  (${uuid(t.id)}, null, true, ${q(t.title)}, ${q(t.icon)}, null, ${int(globalTopicPos)}, ${uuid(groupIds[g.key])})`,
      );
      globalTopicPos++;
    }
  }
  lines.push(topicRows.join(',\n') + ';');
  lines.push('');

  // ===== Courses =====
  lines.push('-- ===== Courses (preset, linked to topics) =====');
  lines.push('insert into public.courses (id, owner_id, is_preset, title, topic_id, icon, position) values');
  const courseRows: string[] = [];
  for (const g of data.groups) {
    for (const t of g.topics) {
      for (const c of t.courses) {
        // Course icon: reuse the topic icon (B&W theme — emojis render flat).
        courseRows.push(
          `  (${uuid(c.id)}, null, true, ${q(c.title)}, ${uuid(t.id)}, ${q(t.icon)}, ${int(c.position)})`,
        );
      }
    }
  }
  lines.push(courseRows.join(',\n') + ';');
  lines.push('');

  // ===== Lessons =====
  lines.push('-- ===== Lessons (preset, linked to courses) =====');
  lines.push('-- duration_seconds = 0 because the import script ran without a YouTube');
  lines.push('-- Data API key. UI renders "—" for zero duration. A future re-run with');
  lines.push('-- YOUTUBE_API_KEY in env will populate real durations.');
  // Single multi-row insert for ~1700 rows is fine for psql.
  lines.push('insert into public.lessons (id, course_id, position, title, yt_id, duration_seconds) values');
  const lessonRows: string[] = [];
  for (const g of data.groups) {
    for (const t of g.topics) {
      for (const c of t.courses) {
        for (const l of c.lessons) {
          lessonRows.push(
            `  (${uuid(l.id)}, ${uuid(c.id)}, ${int(l.position)}, ${q(l.title)}, ${q(l.ytId)}, ${int(l.durationSeconds)})`,
          );
        }
      }
    }
  }
  lines.push(lessonRows.join(',\n') + ';');
  lines.push('');

  await fs.writeFile(OUTPUT_PATH, lines.join('\n'));
  console.log(`Wrote ${OUTPUT_PATH}`);
  console.log(`  ${data.groups.length} groups, ${topicRows.length} topics, ${courseRows.length} courses, ${lessonRows.length} lessons`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
