/**
 * One-shot Khan Academy catalog importer.
 *
 * Reads `docs/research/khan-academy-playlists.json` (532 raw playlists across
 * 65 Khan subjects, scraped via Chrome MCP during brainstorming), filters to
 * the 24 curated subjects in `khan-curated.ts`, then for each playlist fetches
 * the YouTube playlist page and parses `ytInitialData` to extract video IDs +
 * titles.
 *
 * Output: `docs/research/khan-academy-import.json` — committed for review and
 * idempotent re-runs. The seed.sql is generated by a sibling script
 * (`build-seed.ts`) from this intermediate file.
 *
 * No YouTube Data API key required. duration_seconds is set to 0 (existing
 * seed already does this; UI renders "—" for zero-duration lessons). A future
 * pass with `YOUTUBE_API_KEY` can enrich durations via `videos.list`.
 *
 * Usage:
 *   npx tsx scripts/import-khan.ts
 *
 * Idempotent: per-playlist responses are cached on disk so re-runs are free.
 */

import { promises as fs } from 'node:fs';
import { join } from 'node:path';
import { GROUPS, LESSON_CAP, UUID_NS } from './khan-curated';
import { uuidv5 } from './uuid5';

const WORKTREE = process.cwd();
const RESEARCH_DIR = join(WORKTREE, 'docs', 'research');
const INPUT_PATH = join(RESEARCH_DIR, 'khan-academy-playlists.json');
const CACHE_DIR = join(RESEARCH_DIR, '.khan-cache');
const OUTPUT_PATH = join(RESEARCH_DIR, 'khan-academy-import.json');

// ---------- Types ----------

type RawPlaylist = { id: string; sub: string; count: string };
type RawSubject = { subject: string; n: number; items: RawPlaylist[] };
type RawJson = { totalRaw: number; droppedCount: number; subjects: RawSubject[] };

type LessonOut = { id: string; title: string; ytId: string; durationSeconds: number; position: number };
type CourseOut = {
  id: string;
  title: string;
  position: number;
  ytPlaylistId: string;
  truncatedFrom: number | null;
  lessons: LessonOut[];
};
type TopicOut = { id: string; title: string; position: number; icon: string; courses: CourseOut[] };
type GroupOut = { key: string; title: string; position: number; icon: string; topics: TopicOut[] };
type ImportData = { importedAt: string; groups: GroupOut[]; stats: ImportStats };
type ImportStats = {
  totalGroups: number;
  totalTopics: number;
  totalCourses: number;
  totalLessonsRaw: number;
  totalLessonsCapped: number;
  truncatedCourses: number;
  skippedPlaylists: { id: string; reason: string }[];
};

// ---------- Playlist scraping (no API key) ----------

type RawVideoStub = { videoId: string; title: string };

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';

async function fetchPlaylistVideos(playlistId: string, attempt = 0): Promise<RawVideoStub[]> {
  const cachePath = join(CACHE_DIR, `playlist-${playlistId}.json`);
  try {
    const cached = await fs.readFile(cachePath, 'utf8');
    return JSON.parse(cached);
  } catch {/* cache miss */}

  // 1) Initial page load.
  const url = `https://www.youtube.com/playlist?list=${playlistId}&hl=en`;
  const res = await fetch(url, {
    headers: {
      'user-agent': UA,
      'accept-language': 'en-US,en;q=0.9',
      // Pass the consent cookie so we never get redirected to the EU consent splash.
      cookie: 'CONSENT=YES+cb',
    },
  });
  if (!res.ok) {
    if ((res.status === 429 || res.status >= 500) && attempt < 4) {
      await new Promise((r) => setTimeout(r, 1000 * Math.pow(2, attempt)));
      return fetchPlaylistVideos(playlistId, attempt + 1);
    }
    if (res.status === 404) {
      const out: RawVideoStub[] = [];
      await fs.mkdir(CACHE_DIR, { recursive: true });
      await fs.writeFile(cachePath, JSON.stringify(out));
      return out;
    }
    throw new Error(`HTTP ${res.status} fetching playlist ${playlistId}`);
  }
  const html = await res.text();

  const ytInitialData = extractYtInitialData(html);
  const ytcfg = extractYtcfg(html);
  if (!ytInitialData) throw new Error(`no ytInitialData for ${playlistId}`);

  const videos: RawVideoStub[] = [];
  let continuation: string | null = null;
  collectFromInitialData(ytInitialData, videos, (c) => (continuation = c));

  // 2) Paginate via /youtubei/v1/browse if continuation token exists.
  const apiKey = ytcfg?.INNERTUBE_API_KEY;
  const clientName = ytcfg?.INNERTUBE_CONTEXT?.client?.clientName ?? 'WEB';
  const clientVersion = ytcfg?.INNERTUBE_CONTEXT?.client?.clientVersion ?? '2.20240426.01.00';

  let page = 0;
  while (continuation && apiKey && page < 50) {
    page++;
    const browseRes = await fetch(`https://www.youtube.com/youtubei/v1/browse?key=${apiKey}&prettyPrint=false`, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        'user-agent': UA,
        'x-youtube-client-name': '1',
        'x-youtube-client-version': clientVersion,
        'origin': 'https://www.youtube.com',
        cookie: 'CONSENT=YES+cb',
      },
      body: JSON.stringify({
        context: {
          client: { clientName, clientVersion, hl: 'en', gl: 'US' },
        },
        continuation,
      }),
    });
    if (!browseRes.ok) break;
    const data: any = await browseRes.json();
    continuation = null;
    const items = data?.onResponseReceivedActions?.[0]?.appendContinuationItemsAction?.continuationItems
              ?? data?.continuationContents?.playlistVideoListContinuation?.contents
              ?? [];
    for (const it of items) {
      const v = it?.playlistVideoRenderer;
      if (v?.videoId && v?.title) {
        const title = v.title.runs?.[0]?.text ?? v.title.simpleText;
        if (title && title !== 'Private video' && title !== 'Deleted video') {
          videos.push({ videoId: v.videoId, title });
        }
      }
      const cont = it?.continuationItemRenderer?.continuationEndpoint?.continuationCommand?.token;
      if (cont) continuation = cont;
    }
  }

  await fs.mkdir(CACHE_DIR, { recursive: true });
  await fs.writeFile(cachePath, JSON.stringify(videos));
  return videos;
}

function extractYtInitialData(html: string): any | null {
  // YouTube embeds initial data as either `var ytInitialData = {...};` or
  // `window["ytInitialData"] = {...};`. Match the `{...};</script>` boundary.
  const m = html.match(/(?:var ytInitialData|window\["ytInitialData"\])\s*=\s*(\{[\s\S]*?\});/);
  if (!m) return null;
  try { return JSON.parse(m[1]); } catch { return null; }
}

function extractYtcfg(html: string): any | null {
  const m = html.match(/ytcfg\.set\s*\(\s*(\{[\s\S]*?\})\s*\)\s*;/);
  if (!m) return null;
  try { return JSON.parse(m[1]); } catch { return null; }
}

function collectFromInitialData(data: any, out: RawVideoStub[], setCont: (c: string) => void) {
  // Walk to playlistVideoListRenderer.contents.
  const tabs = data?.contents?.twoColumnBrowseResultsRenderer?.tabs ?? [];
  for (const tab of tabs) {
    const sectionList = tab?.tabRenderer?.content?.sectionListRenderer?.contents ?? [];
    for (const section of sectionList) {
      const itemSection = section?.itemSectionRenderer?.contents ?? [];
      for (const it of itemSection) {
        const vlr = it?.playlistVideoListRenderer;
        if (!vlr) continue;
        for (const c of vlr.contents ?? []) {
          const v = c?.playlistVideoRenderer;
          if (v?.videoId) {
            const title = v.title?.runs?.[0]?.text ?? v.title?.simpleText;
            if (title && title !== 'Private video' && title !== 'Deleted video') {
              out.push({ videoId: v.videoId, title });
            }
          }
          const cont = c?.continuationItemRenderer?.continuationEndpoint?.continuationCommand?.token;
          if (cont) setCont(cont);
        }
      }
    }
  }
}

// ---------- Title cleanup ----------

function cleanCourseTitle(raw: string): string {
  // Khan playlist titles often have " | Subject" suffix; strip it.
  return raw.replace(/\s*\|\s*[^|]+$/, '').trim();
}

// ---------- Main ----------

async function main() {
  console.log('Reading research JSON…');
  const raw: RawJson = JSON.parse(await fs.readFile(INPUT_PATH, 'utf8'));
  const subjectIndex = new Map<string, RawSubject>();
  for (const s of raw.subjects) subjectIndex.set(s.subject, s);

  const groups: GroupOut[] = [];
  const stats: ImportStats = {
    totalGroups: 0,
    totalTopics: 0,
    totalCourses: 0,
    totalLessonsRaw: 0,
    totalLessonsCapped: 0,
    truncatedCourses: 0,
    skippedPlaylists: [],
  };

  for (const g of GROUPS) {
    const topicsOut: TopicOut[] = [];
    for (let tIdx = 0; tIdx < g.topics.length; tIdx++) {
      const t = g.topics[tIdx];
      const subj = subjectIndex.get(t.subjectName);
      if (!subj) {
        console.error(`  ! Subject not found in research JSON: "${t.subjectName}" (group ${g.key})`);
        continue;
      }
      console.log(`\n[${g.key}] ${t.subjectName} (${subj.items.length} playlists)`);

      const coursesOut: CourseOut[] = [];
      for (let pIdx = 0; pIdx < subj.items.length; pIdx++) {
        const pl = subj.items[pIdx];
        process.stdout.write(`  [${pIdx + 1}/${subj.items.length}] ${pl.id} ${pl.sub.slice(0, 50)}… `);
        let videos: RawVideoStub[];
        try {
          videos = await fetchPlaylistVideos(pl.id);
        } catch (e: any) {
          console.log(`SKIP (${e.message})`);
          stats.skippedPlaylists.push({ id: pl.id, reason: e.message });
          continue;
        }
        if (videos.length === 0) {
          console.log('SKIP (empty)');
          stats.skippedPlaylists.push({ id: pl.id, reason: 'empty' });
          continue;
        }

        const rawCount = videos.length;
        stats.totalLessonsRaw += rawCount;
        const capped = videos.slice(0, LESSON_CAP);
        const truncated = rawCount > LESSON_CAP ? rawCount : null;
        if (truncated) stats.truncatedCourses++;

        const courseId = uuidv5(`khan:course:${pl.id}`, UUID_NS);
        const lessons: LessonOut[] = capped.map((v, i) => ({
          id: uuidv5(`khan:lesson:${pl.id}:${v.videoId}`, UUID_NS),
          title: v.title,
          ytId: v.videoId,
          // No duration without YOUTUBE_API_KEY; UI renders "—" for 0 (matches existing seed).
          durationSeconds: 0,
          position: i + 1,
        }));
        stats.totalLessonsCapped += lessons.length;

        coursesOut.push({
          id: courseId,
          title: cleanCourseTitle(pl.sub),
          position: pIdx,
          ytPlaylistId: pl.id,
          truncatedFrom: truncated,
          lessons,
        });
        console.log(`OK (${lessons.length}${truncated ? ` of ${truncated}` : ''})`);
      }
      stats.totalCourses += coursesOut.length;

      topicsOut.push({
        id: uuidv5(`khan:topic:${g.key}:${t.subjectName}`, UUID_NS),
        title: t.displayTitle,
        position: tIdx,
        icon: t.icon,
        courses: coursesOut,
      });
    }
    stats.totalTopics += topicsOut.length;

    groups.push({
      key: g.key,
      title: g.title,
      position: g.position,
      icon: g.icon,
      topics: topicsOut,
    });
  }
  stats.totalGroups = groups.length;

  const data: ImportData = { importedAt: new Date().toISOString(), groups, stats };
  await fs.writeFile(OUTPUT_PATH, JSON.stringify(data, null, 2));

  console.log('\n=== Done ===');
  console.log(JSON.stringify(stats, null, 2));
  console.log(`Wrote ${OUTPUT_PATH}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
